### ISSUE TITLE
Zoom of photos - switches photos before reaching the end of the (full) photo

### ISSUE THREAD

**Issue by Linecutterx** [kparuchuri/foto-gallery#1]
Tap a photo. Zoom in (zoom is more limited than using PiGallery direct). Now drag to view the zoomed area that is outside of the current viewport - this triggers the swipe action to move to the next/previous photo.

**Comment by kparuchuri** [comment]
Yeah this is known issue, been trying to fix this past couple of days. Zoom on photos has issues, because of the widgets used. Hope I can come with a clean solution soon.

**Comment by kparuchuri** [comment]
I made some fixes and uploaded a new docker image. Pls test and let me know.
