### ISSUE TITLE
Server addresses

### ISSUE THREAD

**Issue by Linecutterx** [kparuchuri/foto-gallery#2]
"pigallery2 server does not work well with CORS, hence you need to create a new nginx web server in the same domain as your running pigallery2 server"

There's an nginx server in the docker container. It's not clear when I use a reverse proxy whether I should have pigallery.mydomain.tld/foto/ as the address for using foto-gallery, or whether the nginx config is rewriting the URI so that I can use foto.mydomain.tld/foto/ instead.
I imagine that it's the former... Which complicates the reverse proxy config outside of the container!
Could there be an additional env, to pass the foto-gallery subdomain into the nginx config for rewriting to match the pigallery one?

**Comment by kparuchuri** [comment]
Based on what you described, I think its the latter.

The docker container takes care of the reverse proxy configuration inside its nginx configuration.
So if your pigallery2 is already deployed at pigallery2.mydomain.com,  and you deployed the foto docker at foto.mydomain.com,  then you should access foto at http://foto.mydomain.com/foto/.

Internally, what the nginx config does is, any http requests to foto.mydomain.com/* (EXCEPT /foto/) are forwarded to pigallery2.mydomain.com.

**Comment by kparuchuri** [comment]
Closing as there is no more comments
