### ISSUE TITLE
exec /entryPoint.sh: exec format error on unraid

### ISSUE THREAD

**Issue by rhatguy** [kparuchuri/foto-gallery#5]
I loaded your container on unraid using the docker-compose file from the website (only modified the port).  When I start the container I'm getting the following error.  Any idea what would cause this?

root@Tower:~# docker logs -f foto-gallery
exec /entryPoint.sh: exec format error
exec /entryPoint.sh: exec format error
exec /entryPoint.sh: exec format error
exec /entryPoint.sh: exec format error
exec /entryPoint.sh: exec format error
exec /entryPoint.sh: exec format error

**Comment by kparuchuri** [comment]
Hmm, not sure what the issue here is. I use docker on a ubuntu linux instance where I deploy it, on an X86 laptop. Is unraid on ARM by any chance?
BTW I just committed the entire source code to this repo.

**Comment by rhatguy** [comment]
When I do a docker image inspect on the image it tells me this docker image is built for arm64?  I tried on another linux system I had running gentoo.  All of my sysetms are normal intel x86_64 machines.


`# uname -m`
`x86_64`


`# docker image inspect 8bde4411a496`
`.`
`.`
`        "Architecture": "arm64",`
`        "Variant": "v8",`
`        "Os": "linux",`

**Comment by kparuchuri** [comment]
ok, looks like the last push to docker was done from one of my arm machines.  I just pushed another docker image from amd64. Please do a docker pull from latest and try it.
There should not be any differences between arm64 and amd64 images.  Please try it and let me know.

**Comment by rhatguy** [comment]
That definitely fixed the container.  It runs now on my host.  I'm only getting a 404 error now though.  Not sure what thats about as the only configuration option I have that is not in your default docker compose file is the url to my pigallery2....and if I paste that URL into a browser it works.  I'll keep poking.  I think we can close this issue though as the new image has fixed this issue.

**Comment by kparuchuri** [comment]
Closing as resolved.

**Comment by hajo62** [comment]
> ok, looks like the last push to docker was done from one of my arm machines. I just pushed another docker image from amd64. Please do a docker pull from latest and try it. There should not be any differences between arm64 and amd64 images. Please try it and let me know.

@kparuchuri: I've a Pi4 running ubuntu 22.04 and get the same error. What to do?

```
$ docker-compose up foto-gallery
[+] Running 1/0
 ✔ Container foto-gallery  Created                                                                                                                                               0.0s 
Attaching to foto-gallery
foto-gallery  | exec /entryPoint.sh: exec format error
foto-gallery exited with code 0


$ uname -m
aarch64


$ docker image inspect 3b614f8679ac | grep Arch
        "Architecture": "amd64",
```
